#!/bin/bash
#
# Copyright (C) 2018 Mehdi Abaakouk <sileht@sileht.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


DATE=$(date '+%Y%m%d-%H%M')

export SITENAME=$(id -un)
. /omd/sites/${SITENAME}/etc/fastchecker.conf
[ ! "$BASE_DIR" ] && { echo  "BASE_DIR is unset, please fill ~/etc/fastchecker.conf"; exit 1; }
. $BASE_DIR/paths.conf

cleanup() { rmdir $FASTPINGER_TMPPATH/run 2>/dev/null ; }
trap cleanup EXIT
[ ! mkdir $FASTPINGER_TMPPATH/run 2>/dev/null ] && { echo "fastpinger is already running" ; exit 0 ; }

if [[ ! -e ${FASTPINGER_IPSPATH} ]] || [[ ${FASTPINGER_NETWORKSPATH} -nt ${FASTPINGER_IPSPATH} ]]; then
	$BASE_DIR/fastpinger_setup
fi

echo "Start fping $(cat ${FASTPINGER_IPSPATH} | wc -l) hosts..."
cmd="fping --quiet --vcount=5 --period=500 --interval=1 --backoff=1 -f ${FASTPINGER_IPSPATH}"
echo $cmd
$cmd 2> ${FASTPINGER_DUMP}.tmp
mv -f ${FASTPINGER_DUMP}.tmp ${FASTPINGER_DUMP}

FASTPINGER_ARCHIVE=$FASTPINGER_ARCHIVE_PREFIX.$DATE
if [ ! -f ${FASTPINGER_ARCHIVE} ] ; then
	cp -f ${FASTPINGER_DUMP} ${FASTPINGER_ARCHIVE}
	nohup xz -9 ${FASTPINGER_ARCHIVE} &> /dev/null &
fi
echo "Stop fping..."
