#!/bin/bash
#
# Copyright (C) 2018 Mehdi Abaakouk <sileht@sileht.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -o pipefail

DATE=$(date +%s)
SITENAME=$(id -un)
TMP_DIR="/omd/sites/${SITENAME}/tmp/fastpinger"
VAR_DIR="/omd/sites/${SITENAME}/var/fastpinger"
OUTFILE=$TMP_DIR/fastpinger.dump
VARFILE=$TMP_DIR/fastpinger.dump.$DATE

here=$(readlink -f $(dirname $0))
cd $here
mkdir -p $TMP_DIR $VAR_DIR

[ "$1" == "-f" ] && FORCE=1 LOG=1
[ "$1" == "-v" ] && LOG=1

log() { [ "$LOG" ] && echo "$(date --rfc-3339=seconds) : $@"; }

cleanup() {
	rmdir $TMP_DIR/run 2>/dev/null
}
trap cleanup EXIT

if ! mkdir $TMP_DIR/run 2>/dev/null ; then
	log "fastpinger is already running"
	exit 0
fi

if [[ ! -e $TMP_DIR/ips.lst ]] || [[ networks.lst -nt $TMP_DIR/ips.lst ]] || [[ -n "$FORCE" ]]; then
	$here/fastpinger_setup
fi
log "Start fping $(cat $TMP_DIR/ips.lst | wc -l) hosts..."
cmd="fping --quiet --vcount=5 --period=500 --interval=1 --backoff=1 -f $TMP_DIR/ips.lst"
log $cmd
$cmd 2> ${OUTFILE}.tmp
mv -f ${OUTFILE}.tmp ${OUTFILE}
cp -f ${OUTFILE} ${VAR_DIR}
nohup gzip ${VAR_DIR} &> /dev/null &
log "Stop fping..."
