#!/bin/bash
#
# Copyright (C) 2018 Mehdi Abaakouk <sileht@sileht.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


SITENAME=$(id -un)

. /omd/sites/${SITENAME}/etc/fastchecker.conf

if [ ! "$BASE_DIR" ]; then
	echo  "BASE_DIR is unset, please fill ~/etc/fastchecker.conf"
	exit 1
fi

unset LD_LIBRARY_PATH
source $BASE_DIR/venv/bin/activate
exec python $BASE_DIR/$(basename $0).py "$@"
