#!/bin/bash

SITENAME=$(id -un)

. /omd/sites/${SITENAME}/etc/omd/site.conf
. /omd/sites/${SITENAME}/etc/fastchecker.conf

if [ ! "$BASE_DIR" ]; then
	echo  "BASE_DIR is unset, please fill ~/etc/fastchecker.conf"
	exit 1
fi
LOG_DIR="/omd/sites/${SITENAME}/var/log/fastchecker"
TMP_DIR="/omd/sites/${SITENAME}/tmp/fastchecker/gunicorn"
PIDFILE=$TMP_DIR/fastchecker.pid

start_gunicorn() {
	[ "$1" == "test" ] || daemon="--daemon"
	cd $BASE_DIR
	source venv/bin/activate
	gunicorn \
		--name "fastchecker" \
		--bind 127.0.0.1:5001 \
		--worker-class "gevent" \
		--workers $(($(nproc) * 2 + 1)) \
		--timeout 240 \
		--preload \
		--log-file $LOG_DIR/error.log \
		--worker-tmp-dir $TMP_DIR \
		--pid $PIDFILE \
		$daemon \
		fastchecker:app
#		--access-logfile $LOG_DIR/access.log \
	waittime=30
	echo -n 'waiting for pidfile..'
	while [ ! -e "$PIDFILE" ] && [ $waittime -gt 0 ]; do
		echo -n .
		sleep 1
		waiting=$((waiting + 1))
	done
}

case "$1" in
    start|test)
 	echo -n 'Starting fastchecker...'
	if [ -e "$PIDFILE" ] ; then
	    PID=$(cat $PIDFILE)
	    if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
		echo "Already running."
		exit 0
	    fi
	    echo "removing stale pid file..."
	    rm -f $PIDFILE
	fi

	# make sure, directories are there (ramdisk!)
	mkdir -p $TMP_DIR $LOG_DIR && start_gunicorn "$1" && echo OK || echo Error
    ;;
    stop)
	echo -n 'Stopping fastchecker...'
        PID=$(cat $PIDFILE 2>/dev/null)
        if [ -z "$PID" ] ; then
	    echo "not running."
        elif kill "$PID" ; then
            echo -n 'waiting for termination..'
	    N=0
	    while [ -d /proc/$PID ] ; do
		sleep 0.05
                if [ $((N % 20)) -eq 0 ]; then
		    echo -n .
                fi
		N=$((N+1))
		if [ $N -ge 400 ] ; then
		    echo "still running after 20 secs!"
		    exit 1
                fi
	    done    
	    echo "OK"
        else
	    echo "Failed"
        fi
    ;;
    restart|reload)
	$0 stop
	$0 start
    ;;
    status)
	echo -n 'Checking status of fastchecker...'
	if [ -e "$PIDFILE" ] ; then
	    PID=$(cat $PIDFILE)
	    if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
		echo "running"
		exit 0
	    fi
	fi
	echo "stopped"
	exit 1
    ;;
    *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
    ;;
esac


